<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Social Media Team Report</title>
<style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'DejaVu Sans', Arial, sans-serif; font-size: 10px; color: #1e293b; background: #fff; }

    /* Header */
    .header { background: linear-gradient(135deg, #4f46e5, #7c3aed); color: #fff; padding: 20px 24px; margin-bottom: 16px; }
    .header-title { font-size: 20px; font-weight: 700; letter-spacing: -0.5px; }
    .header-sub { font-size: 11px; opacity: 0.85; margin-top: 3px; }
    .header-meta { margin-top: 12px; display: flex; gap: 24px; font-size: 9px; opacity: 0.9; }

    /* Summary cards */
    .summary { display: flex; gap: 10px; margin: 0 24px 16px; }
    .stat-card { flex: 1; border: 1px solid #e2e8f0; border-radius: 8px; padding: 10px 12px; text-align: center; background: #f8fafc; }
    .stat-card .val { font-size: 22px; font-weight: 700; color: #4f46e5; }
    .stat-card .lbl { font-size: 8px; color: #64748b; margin-top: 2px; text-transform: uppercase; letter-spacing: 0.5px; }
    .stat-card.green .val { color: #15803d; }
    .stat-card.amber .val { color: #a16207; }
    .stat-card.blue  .val { color: #1d4ed8; }
    .stat-card.orange .val { color: #c2410c; }

    /* Table */
    .table-wrap { margin: 0 24px 24px; }
    table { width: 100%; border-collapse: collapse; font-size: 8.5px; }
    thead tr { background: #4f46e5; color: #fff; }
    thead th { padding: 7px 8px; text-align: left; font-weight: 600; letter-spacing: 0.3px; white-space: nowrap; }
    tbody tr:nth-child(even) { background: #f8fafc; }
    tbody tr:hover { background: #f1f5f9; }
    tbody td { padding: 6px 8px; border-bottom: 1px solid #e2e8f0; vertical-align: middle; }

    /* Badges */
    .badge { display: inline-block; border-radius: 100px; padding: 2px 7px; font-size: 7.5px; font-weight: 700; }
    .badge-posted   { background: #dcfce7; color: #15803d; }
    .badge-pending  { background: #fef9c3; color: #a16207; }
    .badge-checked  { background: #dbeafe; color: #1d4ed8; }
    .badge-qcp      { background: #ffedd5; color: #c2410c; }
    .badge-na       { background: #f1f5f9; color: #64748b; }

    /* Footer */
    .footer { margin: 0 24px; padding-top: 10px; border-top: 1px solid #e2e8f0; font-size: 8px; color: #94a3b8; text-align: center; }

    .link { color: #4f46e5; word-break: break-all; }
</style>
</head>
<body>

<!-- Header -->
<div class="header">
    <div class="header-title">📱 Social Media Team Report</div>
    <div class="header-sub">DGT System — Digital Team Management</div>
    <div class="header-meta">
        <span>📅 Period: {{ \Carbon\Carbon::parse($dateFrom)->format('d M Y') }} – {{ \Carbon\Carbon::parse($dateTo)->format('d M Y') }}</span>
        <span>👤 Generated by: {{ $generatedBy }}</span>
        <span>🕒 Generated: {{ $generatedDate }}</span>
    </div>
</div>

<!-- Summary -->
<div class="summary">
    <div class="stat-card">
        <div class="val">{{ $summary['total'] }}</div>
        <div class="lbl">Total Tasks</div>
    </div>
    <div class="stat-card green">
        <div class="val">{{ $summary['posted'] }}</div>
        <div class="lbl">Posted</div>
    </div>
    <div class="stat-card amber">
        <div class="val">{{ $summary['pending'] }}</div>
        <div class="lbl">Pending</div>
    </div>
    <div class="stat-card blue">
        <div class="val">{{ $summary['checked'] }}</div>
        <div class="lbl">QC Checked</div>
    </div>
    <div class="stat-card orange">
        <div class="val">{{ $summary['qcPending'] }}</div>
        <div class="lbl">QC Pending</div>
    </div>
</div>

<!-- Table -->
<div class="table-wrap">
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Date</th>
                <th>Class</th>
                <th>Social Media</th>
                <th>Post Status</th>
                <th>Post Link</th>
                <th>Submitted By</th>
                <th>Submitted At</th>
                <th>QC Status</th>
                <th>Checked By</th>
                <th>Checked At</th>
            </tr>
        </thead>
        <tbody>
            @forelse($tasks as $i => $task)
            <tr>
                <td>{{ $i + 1 }}</td>
                <td style="white-space:nowrap">{{ $task->task_date->format('d M Y') }}</td>
                <td>{{ $task->socialMediaClass->name ?? '—' }}</td>
                <td>{{ $task->socialMediaItem->name ?? '—' }}</td>
                <td>
                    @if($task->is_posted)
                        <span class="badge badge-posted">Posted</span>
                    @else
                        <span class="badge badge-pending">Pending</span>
                    @endif
                </td>
                <td>
                    @if($task->post_url)
                        <span class="link">{{ $task->post_url }}</span>
                    @else
                        —
                    @endif
                </td>
                <td>{{ $task->poster?->name ?? '—' }}</td>
                <td style="white-space:nowrap">{{ $task->posted_at?->format('d M Y H:i') ?? '—' }}</td>
                <td>
                    @if($task->is_checked)
                        <span class="badge badge-checked">Checked</span>
                    @elseif($task->is_posted)
                        <span class="badge badge-qcp">QC Pending</span>
                    @else
                        <span class="badge badge-na">—</span>
                    @endif
                </td>
                <td>{{ $task->checker?->name ?? '—' }}</td>
                <td style="white-space:nowrap">{{ $task->checked_at?->format('d M Y H:i') ?? '—' }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="11" style="text-align:center;padding:20px;color:#94a3b8;">No data found.</td>
            </tr>
            @endforelse
        </tbody>
    </table>
</div>

<!-- Footer -->
<div class="footer">
    This report was generated automatically by DGT System. | Confidential — For internal use only.
</div>

</body>
</html>
