<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Social Media Team Report</title>
<style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'DejaVu Sans', Arial, sans-serif; font-size: 10px; color: #1e293b; background: #fff; }

    /* Header */
    .header { background: #1e293b; color: #fff; padding: 24px 24px; margin-bottom: 20px; border-bottom: 4px solid #4f46e5; }
    .header-title { font-size: 22px; font-weight: 700; letter-spacing: 0.5px; text-transform: uppercase; }
    .header-sub { font-size: 10px; opacity: 0.85; margin-top: 4px; letter-spacing: 0.5px; }
    .header-meta { margin-top: 12px; display: flex; gap: 24px; font-size: 9px; opacity: 0.9; }

    /* Summary cards */
    .summary-wrap { margin: 0 24px 20px; }
    .summary-table { width: 100%; table-layout: fixed; border-collapse: collapse; }
    .stat-card-cell { width: 20%; padding-right: 10px; vertical-align: top; }
    .stat-card-cell:last-child { padding-right: 0; }
    .stat-card { border: 1px solid #cbd5e1; border-radius: 6px; padding: 12px 10px; text-align: center; background: #f8fafc; }
    .stat-card .val { font-size: 22px; font-weight: 700; color: #334155; }
    .stat-card .lbl { font-size: 8px; color: #64748b; margin-top: 4px; text-transform: uppercase; letter-spacing: 0.5px; font-weight: bold; }
    .stat-card.green .val { color: #16a34a; }
    .stat-card.amber .val { color: #d97706; }
    .stat-card.blue  .val { color: #2563eb; }
    .stat-card.orange .val { color: #ea580c; }

    /* Table */
    .table-wrap { margin: 0 24px 24px; }
    table { width: 100%; border-collapse: collapse; font-size: 8.5px; }
    thead tr { background: #4f46e5; color: #fff; }
    thead th { padding: 7px 8px; text-align: left; font-weight: 600; letter-spacing: 0.3px; white-space: nowrap; }
    tbody tr:nth-child(even) { background: #f8fafc; }
    tbody tr:hover { background: #f1f5f9; }
    tbody td { padding: 6px 8px; border-bottom: 1px solid #e2e8f0; vertical-align: middle; }

    /* Badges */
    .badge { display: inline-block; border-radius: 100px; padding: 2px 7px; font-size: 7.5px; font-weight: 700; }
    .badge-posted   { background: #dcfce7; color: #15803d; }
    .badge-pending  { background: #fef9c3; color: #a16207; }
    .badge-checked  { background: #dbeafe; color: #1d4ed8; }
    .badge-qcp      { background: #ffedd5; color: #c2410c; }
    .badge-na       { background: #f1f5f9; color: #64748b; }

    /* Footer */
    .footer { margin: 0 24px; padding-top: 10px; border-top: 1px solid #e2e8f0; font-size: 8px; color: #94a3b8; text-align: center; }

    .link { color: #4f46e5; word-break: break-all; }
</style>
</head>
<body>

<!-- Header -->
<div class="header">
    <div class="header-title">📱 Social Media Team Report</div>
    <div class="header-sub">KIUQ SYSTEM — Digital Team Management</div>
    <div class="header-meta">
        <span>📅 Period: {{ \Carbon\Carbon::parse($dateFrom)->format('d M Y') }} – {{ \Carbon\Carbon::parse($dateTo)->format('d M Y') }}</span>
        <span>👤 Generated by: {{ $generatedBy }}</span>
        <span>🕒 Generated: {{ $generatedDate }}</span>
    </div>
</div>

<!-- Summary -->
<div class="summary-wrap">
    <table class="summary-table" cellspacing="0" cellpadding="0">
        <tr>
            <td class="stat-card-cell">
                <div class="stat-card">
                    <div class="val">{{ $summary['total'] }}</div>
                    <div class="lbl">Total Tasks</div>
                </div>
            </td>
            <td class="stat-card-cell">
                <div class="stat-card green">
                    <div class="val">{{ $summary['completed'] }}</div>
                    <div class="lbl">Posted</div>
                </div>
            </td>
            <td class="stat-card-cell">
                <div class="stat-card amber">
                    <div class="val">{{ $summary['pending'] }}</div>
                    <div class="lbl">Pending</div>
                </div>
            </td>
            <td class="stat-card-cell">
                <div class="stat-card blue">
                    <div class="val">{{ $summary['checked'] }}</div>
                    <div class="lbl">QC Checked</div>
                </div>
            </td>
            <td class="stat-card-cell">
                <div class="stat-card orange">
                    <div class="val">{{ $summary['qcPending'] }}</div>
                    <div class="lbl">QC Pending</div>
                </div>
            </td>
        </tr>
    </table>
</div>

<!-- Table -->
<div class="table-wrap">
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Date</th>
                <th>Class</th>
                <th>Social Media</th>
                <th>Post Status</th>
                <th>Link Entered</th>
                <th>Text/Content Entered</th>
                <th>Submitted By</th>
                <th>Submitted At</th>
                <th>QC Status</th>
                <th>Checked By</th>
                <th>Checked At</th>
            </tr>
        </thead>
        <tbody>
            @forelse($posts as $i => $post)
            <tr>
                <td>{{ $i + 1 }}</td>
                <td style="white-space:nowrap">{{ $post->post_date->format('d M Y') }}</td>
                <td>{{ $post->socialMediaClass->name ?? '—' }}</td>
                <td>{{ $post->socialMediaItem->name ?? '—' }}</td>
                <td>
                    @if($post->is_completed)
                        <span class="badge badge-posted">Posted</span>
                    @else
                        <span class="badge badge-pending">Pending</span>
                    @endif
                </td>
                <td>
                    @if($post->post_url)
                        <span class="link">{{ $post->post_url }}</span>
                    @else
                        —
                    @endif
                </td>
                <td>
                    @if($post->optional_text)
                        <div style="max-height: 40px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; max-width: 100px;">
                            {{ $post->optional_text }}
                        </div>
                    @else
                        —
                    @endif
                </td>
                <td>{{ $post->user?->name ?? '—' }}</td>
                <td style="white-space:nowrap">{{ $post->completed_at?->format('d M Y H:i') ?? '—' }}</td>
                <td>
                    @if($post->is_checked)
                        <span class="badge badge-checked">Checked</span>
                    @elseif($post->is_completed)
                        <span class="badge badge-qcp">QC Pending</span>
                    @else
                        <span class="badge badge-na">—</span>
                    @endif
                </td>
                <td>{{ $post->checker?->name ?? '—' }}</td>
                <td style="white-space:nowrap">{{ $post->checked_at?->format('d M Y H:i') ?? '—' }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="12" style="text-align:center;padding:20px;color:#94a3b8;">No data found.</td>
            </tr>
            @endforelse
        </tbody>
    </table>
</div>

<!-- Footer -->
<div class="footer">
    This report was generated automatically by KIUQ SYSTEM. | Confidential — For internal use only.
</div>

</body>
</html>
